dist: bionic

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

  # command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install

script: pytest test/

branches:
  only:
    - master